---
name: "terraform apply"

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"  # apply config daily

jobs:
  terraform:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: hashicorp/setup-terraform@v3
      - run: "terraform init"
      - run: "terraform apply -auto-approve"
